---
title: "Identifying nests and swallows based on spatiotemporal wild boar data."
subtitle: "Project Works Patterns and Trends in Environmental Data"
author: "Yves Gubelmann and Tobias Wildhaber"
date: "4 July, 2021"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: darkly
    highlight: tango
    code_folding: hide
---

<!-- You can add  your R Code with Code chunks-->

```{r chunk settings, echo = TRUE, warning=FALSE, message=FALSE}

# You can set chunk options individually per code chunk, as was done with this
# code chunk.

# echo = FALSE           hides the code from the generated output
# warning = FALSE        hides warnings from the generated output
# message = FALSE        hides messages from the generated output

# To set the setting for all code chunks, use the following code:

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

# Abstract

<!-- the following is just a placeholder text, remove it!-->

Text

# Introduction

<!-- the following is just a placeholder text, remove it!-->

Text

```{r placeholder 1}
library(ComputationalMovementAnalysisData)
library(ggplot2)

# Include tables with the function "kable"

knitr::kable(head(wildschwein_BE))
```

<!-- the following is just a placeholder text, remove it!-->

Text

```{r placeholder 2}
# include plots automatically

ggplot(schreck_locations, aes(E, N)) +
  geom_point() +
  coord_map()

```

# Material and Methods

## Data

## Analytical Concepts

## R Concecpts

<!-- the following is just a placeholder text, remove it!-->

Text

# Results

<!-- the following is just a placeholder text, remove it!-->

Text

# Discussion

## Risk analysis / Problems

<!-- the following is just a placeholder text, remove it!-->

Text

# References

Text

# Annex

R Script

```{r source code, echo=FALSE}

# source("scripts/analysis.r")

```
